data:
  name: wenetspeech
  vocab: egs/wenetspeech/vocab
  dataset_type: wenetspeech # kaldi, online, wenetspeech or espnet
  data_type: shard
  train_path: dump/corpus/aishell_wenetspeech/train/data.list
  # train_path: dump/corpus/aishell_wenetspeech/train/data.list
  test_path: dump/corpus/aishell/test/data86.list
  # test_path: egs/wenetspeech/data/dev/data.list
  normalization: True
  global_cmvn: dump/corpus/aishell/train/global_cmvn_80 # 用的是 aishell 数据集提取出的 cmvn
  volume_perturb: True
  speed_perturb: True
  gaussian_noise: 0.10
  filter_conf:
    max_length: 1200
    min_length: 10
    token_max_length: 100
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  fbank_conf:
    num_mel_bins: 80
    frame_shift: 10
    frame_length: 25
    dither: 0.0 # 1.0 not used for our wav hasn't been left shifted
  spec_aug: True
  spec_aug_conf:
    freq_mask_num: 2
    time_mask_num: 5
    freq_mask_rate: 0.3
    time_mask_rate: 0.05
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 1000
  batch_conf:
    batch_type: 'static' # static or dynamic
    batch_size: 32
  pin_memory: true
  num_workers: 4
  prefetch: 96
model:
  type: speech2text
  frontend_type: conv
  frontend:
    input_size: 80
    output_size: 384
    in_channel: 1
    mid_channel: 128
    out_channel: 256
    kernel_size: [[3,3],[3,3]]
    stride: [2, 2]
    dropout: 0.0
    act_func_type: relu
    front_end_layer_norm: False
  encoder_type: conformer
  encoder:
    d_model: 384
    d_ff: 2048
    cov_kernel_size: 15
    n_heads: 4
    nblocks: 12
    pos_dropout: 0.0
    slf_attn_dropout: 0.0
    ffn_dropout: 0.0
    residual_dropout: 0.1
    conv_dropout: 0.0
    macaron_style: True
    ffn_scale: 0.5
    conv_bias: True
    activation: glu
    relative_positional: True
  decoder_type: transformer
  decoder:
    vocab_size: 5501
    d_model: 384
    n_heads: 4
    d_ff: 2048
    memory_dim: 384
    n_blocks: 6
    pos_dropout: 0.0
    slf_attn_dropout: 0.0
    src_attn_dropout: 0.0
    ffn_dropout: 0.0
    residual_dropout: 0.1
    activation: glu
    normalize_before: False
    concat_after: False
    share_embedding: True
    relative_positional: False
  ctc_weight: 0.2
  encoder_output_size: 384
  smoothing: 0.1
train:
  optimizer_type: adam
  optimizer:
    lr: 0.0007
    betas: [0.9, 0.98]
    eps: 1.0e-9
    weight_decay: 1.0e-6
    amsgrad: False
  scheduler_type: conformer
  scheduler:
    warmup_steps: 12000
  clip_grad: 5
  epochs: 40
  accum_steps: 4
  grad_noise: 0.0
  load_model: False
  save_name: Conformer_CTC_CMVN
